apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: custom-static-path
provisioner: viz.software/static-path-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
    storagePath: /srv/k0s-volume
