apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: static-path
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: viz.software/static-path-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
